import type { VehicleState, DriveMode } from './types';

export const defaultState: VehicleState = {
  odometer: 0.0,
  tripA: 0.0,
  tripB: 0.0,
  activeTrip: 'A',
  batterySOC: 100.0,
  driveMode: 'Eco',
  acOn: false,
  acTemp: 22,
  chargingLogs: [],
  speed: 0,
  power: 0,
  efficiency: 0,
  ecoScore: 85,
  batteryCapacity_kWh: 50,
  lastUpdate: Date.now(),
  displaySpeed: 0,
  outsideTemp: 25,
  insideTemp: 25,
  speedHistory: [],
  accelerationHistory: [],
  powerHistory: [],
  energyConsumptionHistory: [],
  driveModeHistory: [],
  lastStyleClassificationTime: 0,
  aggressiveDrivingCounter: 0,
  stabilizerEnabled: true,
  rawPredictedRange: null,
  sohHistory: [],
  packNominalCapacity_kWh: 50,
  packUsableFraction: 0.92,
  packSOH: 100,
  equivalentFullCycles: 0,
  cumulativeEnergyOut_kWh: 0,
  cumulativeEnergyIn_kWh: 0,
  batteryTemp: 30,
  drivetrainEfficiency: 0.9,
  regenEfficiencyDynamic: 0.85,
  thermalThrottleFactor: 1.0,
  regenLimitFactor: 1.0,
  recentWhPerKm: 0,
  recentWhPerKmWindow: [],
  styleMetrics: {
    aggression: 0,
    smoothness: 1,
    regenShare: 0,
    harshEvents: 0,
    harshBrakes: 0,
    harshAccel: 0,
  },
  lastDegradationUpdate: 0,
  lastRangeModelUpdate: 0,
  predictedEcoRange: 0,
  predictedDynamicRange: 443,
  limpMode: false,
  powerLimit_kW: 0,
  voltageNominal: 360,
  internalResistance: 0.08,
  lastSOHUpdate: 0,
  lastRangeSpeed: 0,
  lastRawDynamicRange: null,
  isCharging: false,
  profiles: {
    'Pritesh': { driveMode: 'Eco', acTemp: 22 },
    'Alex Doe': { driveMode: 'Eco', acTemp: 22 },
    'Ben Smith': { driveMode: 'City', acTemp: 20 },
    'Chloe Ray': { driveMode: 'Sports', acTemp: 24 },
  },
  activeProfile: 'Pritesh',
  weather: null,
  sohForecast: [],
  drivingRecommendation: 'Start driving to get recommendations.',
  drivingStyle: 'Balanced',
  drivingStyleRecommendations: [],
};

export const EV_CONSTANTS = {
  mass_kg: 1850,
  frontalArea_m2: 2.25,
  dragCoeff: 0.27,
  airDensity: 1.204,
  rollingResistanceCoeff: 0.010,
  gravity: 9.806,
  accessoryBase_kW: 0.25,
  accessoryVariance_kW: 0.15,
  maxDrivePower_kW: 160,
  maxRegenPower_kW: 70,
  coldTempPenaltyStart: 15,
  hotTempPenaltyStart: 40,
  coldTempRegenLimit: 10,
  minUsableSOC: 6,
  limpModeSOC: 5,
  thermalThrottleTemp: 48,
  criticalTemp: 55,
  degradationCycleCoeff: 0.035,
  degradationTempHotCoeff: 0.00004,
  degradationTempColdCoeff: 0.00001,
  smoothingRange: 0.15,
  whPerKmBasePoly: {
    a: 0.012,
    b: 0.2,
    c: 85,
  },
};

export const MODE_SETTINGS: Record<
  DriveMode,
  {
    maxSpeed: number;
    accelRate: number;
    decelRate: number;
    brakeRate: number;
    regenEfficiency: number;
    powerFactor: number;
    rangeFactor: number;
  }
> = {
  Eco: {
    maxSpeed: 45,
    accelRate: 12.0,
    decelRate: 8.0,
    brakeRate: 20,
    regenEfficiency: 0.9,
    powerFactor: 0.6,
    rangeFactor: 1.25,
  },
  City: {
    maxSpeed: 75,
    accelRate: 18,
    decelRate: 10,
    brakeRate: 25,
    regenEfficiency: 0.75,
    powerFactor: 1.0,
    rangeFactor: 1.0,
  },
  Sports: {
    maxSpeed: 120,
    accelRate: 30,
    decelRate: 12,
    brakeRate: 35,
    regenEfficiency: 0.55,
    powerFactor: 1.6,
    rangeFactor: 0.75,
  },
};
